export default {
  //默认页面以及请求借口URL
  DEFAULT_URL: '',
  DEFAULT_INTERFACE_URL: '',

  //cookie
  COOKIE_USER_ID: "USERID",
  COOKIE_USER_NAME: "USERNAME",
  COOKIE_USER_HEAD: "HEADICON",
  COOKIE_USER_SESSIONKEY: "USER_SESSIONKEY",
  COOKIE_USER_MOBILE: "MOBILE",
  COOKIE_USER_THIRD_ID: "USER_THIRDID",
  COOKIE_USER_INFO_FILL: "USER_INFO_FILL",
  COOKIE_USER_INVITE_CODE: "INVITE_CODE",
  COOKIE_CITYID: "CITYID",
  COOKIE_X_CLIENT_INFO: "X-Client-Info",
  COKKIE_DEBUG: "DEBUG",

  //default
  DEFAULT_CLIENT_TYPE: 4,
  DEFAULT_VERSION: "1.4.1",

  //setion
  ADD_SCORE: 0.1,
  INVITE_SCORE: 5
}